### ISSUE TITLE
CMakeLists.txt should search for Manycore .so/headers in /usr/lib and /usr/include and use BSG_F1_DIR as backup

### ISSUE THREAD

**Issue by drichmond** [bespoke-silicon-group/tvm#1]
https://github.com/bespoke-silicon-group/tvm/blob/19b8e76a368967c0cda64166b0e05f2ffd189da3/CMakeLists.txt#L207

Since the BSG Manycore Libraries are installed in the linux file system, it is standard practice to link against them there. This will remove the environment variable dependence. 

Alternatively, it we could have another variable for COSIM, that defines the search path for the libraries and include files.

**Comment by cylinbao** [comment]
Addressed in the commit 323dcbf.
Now the tvm code base doesn't rely on environment variables.
